name: setting up environment

on: [push]
    
env:
 username: RealmeFirmwareUpdater
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@main

       - name: initialization
         continue-on-error: true
         run: |
           sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
           docker rmi `docker images -q`
           git config --global user.name "AOSP_BOT"
           git config --global user.email "aospbot@techyminati.com"         
           sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
           sudo -E apt-get clean 
           sudo apt install expect -y
           sudo -E pip3 install setuptools
           
       - name: cloning repo
         continue-on-error: true
         run: |
           expect -c " 
           spawn git clone ${{ secrets.REPOM }} source
           expect \"Username\"        
           send \"${{ secrets.GHUSER }}\r\"
           expect \"Password\"        
           send \"${{ secrets.GHPASS }}\r\"
           set timeout -1
           catch wait result
           interact"

       - name: compilation
         continue-on-error: true
         run: |
           ls
           cd source
           sudo pip3 install setuptools
           sudo pip3 install -r requirements.txt
           
       - name: running Docker
         timeout-minutes: 340
         continue-on-error: true
         run: |
           cd source
           python3 aosp_tracker.py
           
       - name: Loop workflow
         continue-on-error: true
         run: |
              git clone https://github.com/$username/aosp-workflow loop
              cd loop
              echo "1" >> loop.txt
              git add loop.txt
              git commit -m "Workflow : Loop"
              expect -c "
              spawn git push -f 
              expect \"Username\"
              send \"${{ secrets.GHUSER }}\r\"
              expect \"Password\"
              send \"${{ secrets.GHPASS }}\r\"
              expect \"main -> main\"
              set timeout -10
              interact"
              
